version: "3.9"

name: "walmir-dev"

services:
  postgres:
    image: postgres:15.1-alpine
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgresql-data:/var/lib/postgresql/data
