# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby File.read(".ruby-version").strip

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "~> 7.0.4", ">= 7.0.4.3"
# https://github.com/svenfuchs/rails-i18n#configuration
gem "rails-i18n", "~> 7.0"
# Use postgres as the database for Active Record
gem "pg", "~> 1.2", ">= 1.2.3"
# https://github.com/puma/puma#rails
gem "puma", "~> 5.4"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem "rack-cors"

group :development, :test do
  # https://github.com/bkeepers/dotenv#rails
  gem "dotenv-rails", "~> 2.7", ">= 2.7.6"
  # https://github.com/rweng/pry-rails#usage
  gem "pry-rails", "~> 0.3.9"
  # https://github.com/flyerhzm/bullet
  gem "bullet", "~> 7.0", ">= 7.0.1"
  # https://github.com/rubocop-hq/rubocop-rails#usage
  gem "rubocop-rails", "~> 2.11", ">= 2.11.3"
  # https://github.com/rubocop-hq/rubocop-performance#usage
  gem "rubocop-performance", "~> 1.11", ">= 1.11.4"
  # https://github.com/backus/rubocop-rspec
  gem "rubocop-rspec", "~> 2.4"
  # https://github.com/DmitryTsepelev/rubocop-graphql#usage
  gem "rubocop-graphql", "~> 1.1"
  # https://github.com/thoughtbot/factory_bot_rails
  gem "factory_bot_rails", "~> 6.2"
  # https://github.com/stympy/faker
  gem "faker", "~> 2.18"
end

group :test do
  # https://github.com/rspec/rspec-rails#installation
  gem "rspec-rails", "~> 5.0", ">= 5.0.1"
  # https://github.com/thoughtbot/shoulda-matchers
  gem "shoulda-matchers", "~> 5.0"
  # https://github.com/DatabaseCleaner/database_cleaner
  gem "database_cleaner", "~> 2.0", ">= 2.0.1"
end
