name: GitLab Synchronization

on: [push, delete]

jobs:
  sync:
    runs-on: ubuntu-latest
    name: GitLab synchronization
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: owalmirneto/git-repo-sync@v0.1.1
      with:
        target-domain: gitlab.com
        target-username: owalmirneto
        target-repository: walmir.dev
        target-token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
