name: RSpec

on:
  workflow_call:

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-22.04

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:@localhost:5432/walmir_dev_test

    services:
      db:
        image: postgres:15.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Verify ruby version
        working-directory: ./apps/backend
        run: ruby --version

      - name: Copy .env
        run: cp ./apps/backend/.env.example ./apps/backend/.env

      - name: Install bundler
        working-directory: ./apps/backend
        run: gem install bundler && bundler install

      - name: Prepare database
        working-directory: ./apps/backend
        run: bin/rails db:setup db:test:prepare db:schema:load db:migrate --trace RAILS_ENV=test;

      - name: Run RSpec
        working-directory: ./apps/backend
        run: bin/rspec
