name: Next.js Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint with pnpm
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8

      - name: Install dependencies
        working-directory: apps/frontend
        run: pnpm install

      - name: Frontend Lint
        working-directory: apps/frontend
        run: pnpm lint
