name: Sync infrastructure

on:
  push:
    branches: [main]

jobs:
  ci:
    uses: ./.github/workflows/continuous-integration.yml

  terraform:
    name: Sync infrastructure with Terraform
    runs-on: ubuntu-22.04
    needs: [ci]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_ssh_public_key_content: ${{ secrets.SSH_PUBLIC_KEY_CONTENT }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init -backend-config="conn_str=${{ secrets.TERRAFORM_PG_CONNECTION }}" -input=false

      - name: Terraform validation
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform plan
        working-directory: ./terraform
        run: terraform plan -input=false

      - name: Terraform apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -input=false

      - name: Create ssh private key
        working-directory: ./ansible
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY_CONTENT }}" > ssh/private-key.pem
          chmod 0600 ssh/private-key.pem

      - name: Install dependecies with Ansible
        working-directory: ./ansible
        run: ansible-playbook --private-key=ssh/private-key.pem main.yaml
